"""
Data models for S.O.F.I.E. Backend.
Privacy-first schemas with consent enforcement.
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime
from enum import Enum


class ConsentType(str, Enum):
    """Types of consent required for different operations."""
    WELLNESS_GUIDANCE = "wellness_guidance"
    DATA_STORAGE = "data_storage"
    ANALYTICS = "analytics"


class ConsentStatus(str, Enum):
    """Consent status values."""
    GRANTED = "granted"
    DENIED = "denied"
    EXPIRED = "expired"
    REVOKED = "revoked"


class ConsentRequest(BaseModel):
    """Request to grant consent for a specific operation."""
    user_id: str = Field(..., description="Unique user identifier")
    consent_type: ConsentType = Field(..., description="Type of consent being granted")
    purpose: str = Field(..., description="Clear description of what the consent is for")
    
    class Config:
        json_schema_extra = {
            "example": {
                "user_id": "user_123",
                "consent_type": "wellness_guidance",
                "purpose": "Receive personalized wellness guidance based on my context"
            }
        }


class ConsentResponse(BaseModel):
    """Response after granting or checking consent."""
    user_id: str
    consent_type: ConsentType
    status: ConsentStatus
    granted_at: Optional[datetime] = None
    expires_at: Optional[datetime] = None
    
    class Config:
        json_schema_extra = {
            "example": {
                "user_id": "user_123",
                "consent_type": "wellness_guidance",
                "status": "granted",
                "granted_at": "2024-01-25T12:00:00Z",
                "expires_at": "2024-01-26T12:00:00Z"
            }
        }


class WellnessContext(BaseModel):
    """Context information for wellness guidance requests."""
    mood: Optional[str] = Field(None, description="Current mood or emotional state")
    energy_level: Optional[int] = Field(None, ge=1, le=10, description="Energy level (1-10)")
    sleep_quality: Optional[int] = Field(None, ge=1, le=10, description="Sleep quality (1-10)")
    stress_level: Optional[int] = Field(None, ge=1, le=10, description="Stress level (1-10)")
    recent_activities: Optional[List[str]] = Field(None, description="Recent activities or events")
    goals: Optional[List[str]] = Field(None, description="Current wellness goals")


class WellnessRequest(BaseModel):
    """Request for wellness guidance with consent verification."""
    user_id: str = Field(..., description="Unique user identifier")
    query: str = Field(..., description="Wellness question or guidance request")
    context: Optional[WellnessContext] = Field(None, description="Optional context for personalization")
    
    class Config:
        json_schema_extra = {
            "example": {
                "user_id": "user_123",
                "query": "What are some gentle exercises I can do to reduce stress?",
                "context": {
                    "mood": "anxious",
                    "energy_level": 5,
                    "stress_level": 7,
                    "goals": ["reduce stress", "improve sleep"]
                }
            }
        }


class WellnessResponse(BaseModel):
    """Response with wellness guidance."""
    guidance: str = Field(..., description="Wellness guidance generated by LLaMA")
    context_used: bool = Field(..., description="Whether user context was used")
    consent_verified: bool = Field(..., description="Whether consent was verified before processing")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        json_schema_extra = {
            "example": {
                "guidance": "Based on your context, here are some gentle stress-reduction exercises...",
                "context_used": True,
                "consent_verified": True,
                "timestamp": "2024-01-25T12:00:00Z"
            }
        }


class HealthCheckResponse(BaseModel):
    """Health check response."""
    status: str = "healthy"
    version: str = "1.0.0"
    llama_available: bool = False
    consent_enforcement: bool = True
